myapp/urls.py
from myapp import user_views
from myapp.user_views import register_user
from django.conf.urls import url
# from django.urls.resolvers import URLPattern
from django.contrib.auth import views as auth_views # đổi tên cho khỏi trùng views dưới
from .import views # file urls.py và views.py cùng 1 folder
from .import base_class_views
urlpatterns = [
    # URl cua Ham
    url(r"^$", views.index , name="index"),   #^$ là bắt đầu và kết thúc luôn thì nó rỗngn :))
    url(r"^list-author$", views.list_author, name="list_author"),
    url(r"^add-author$",views.add_author, name='add_author'),
    url(r"^add-book$",views.add_book, name='add_book'),
    url(r"^author/(?P<author_id>[0-9]+)$",views.view_detail_author, name="view_detail_author" ),
    url(r"^update-author/(?P<author_id>[0-9]+)$", views.update_author, name= "update_author"),
    url(r"^delete-author/(?P<author_id>[0-9]+)$", views.delete_author, name= "delete_author"),
    url(r"^home$", views.home, name="home"),

    # Class Base View
    url(r"^all-author$",base_class_views.AuthorListView.as_view(), name="all-author"),
    url(r"^view-author/(?P<pk>[0-9]+)$", base_class_views.AuthorDetailView.as_view(), name='view-author'),
    url(r"^insert-author$", base_class_views.AuthorCreateView.as_view(), name='insert-author'),
    url(r"^edit-author/(?P<pk>[0-9]+)$",base_class_views.AuthorUpdateView.as_view(), name='edit-author'),
    url(r"^remove-author/(?P<pk>[0-9]+)$",base_class_views.AuthorDeleteView.as_view(), name='remove-author'),

    #User authentication/authorization
    url(r"^register$",user_views.register_user, name='register'),
    url(r"^login$",user_views.login_user, name='login'),
    url(r"^logout$", auth_views.LogoutView.as_view(next_page="/"),name='logout_user'),
    url(r"^change-password$", auth_views.PasswordChangeView.as_view(template_name="user/change_password.html"),name='change_password'),

]

myweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    url(r"^", include("myapp.urls")),
    path('admin/', admin.site.urls),
]

myapp/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):
        return self.first_name
    class Meta:
        db_table='Author'


class Book(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    class Meta:
        db_table="Book"

myapp/forms.py
# from django.db.models import fields
from django.forms import ModelForm,widgets,Form
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Book,Author

class AuthorForm(ModelForm):
    class Meta:
        model= Author
        fields = "__all__"
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }
        
    def clean_email(self): # validation cho thuộc tính của author
        input_email = self.cleaned_data['email']
        try:
            Author.objects.get(email=input_email) # Lấy report theo email
        except Author.DoesNotExist:
            return input_email
        raise ValidationError(f"{input_email} đã tồn tại. Mời bạn nhập mail khác")

class Bookform(ModelForm):
    class Meta:
        model= Book
        fields = '__all__'
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'pub_date':forms.DateInput(attrs={'class':'form-control','type' : 'date'}),
            'author':forms.Select(attrs={'class':'form-control'}),
        }

class RegisterForm(Form):
    first_name = forms.CharField(
        label="Tên",
        widget=forms.TextInput(
             attrs={
                'class':'form-control',
                'id':'first_name'
            }
        )
    )

    last_name = forms.CharField(
        label="Họ",
        widget=forms.TextInput(
             attrs={
                'class':'form-control',
                'id':'last_name'
            }
        )
    )

    username = forms.CharField(
        label="Tên Đăng Nhập",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'id':'username'
            }
        )
    )

    password = forms.CharField(
        label="Mật Khẩu",
        widget=forms.PasswordInput(
             attrs={
                'class':'form-control',
                'id':'password'
            }
        )
    )

    confirm_password = forms.CharField(
        label="Nhập Lại Mật Khẩu",
        widget=forms.PasswordInput(
             attrs={
                'class':'form-control',
                'id':'confirm_password'
            }
        )
    )
  
    email = forms.EmailField(
        label="Email Đăng Ký",
        widget=forms.EmailInput(
             attrs={
                'class':'form-control',
                'id':'email'
            }
        )
    )


# Validation :username , email không được trùng có sẵn trong DB
# password và confirm_password là phải giống nhau(Kiểm tra ở phí client, javascrip)
# Ta tạo hàm
    def clean_username(self):
        inputed_username = self.cleaned_data['username']
        try:
            User.objects.get(username=inputed_username)
            raise ValidationError(f"{inputed_username} đã tồn tại")
        except User.DoesNotExist:
            return inputed_username
    def clean_email(self):
        inputed_email = self.cleaned_data['email']
        try:
            User.objects.get(email=inputed_email)
            raise ValidationError(f"{inputed_email} đã tồn tại")
        except User.DoesNotExist:
            return inputed_email
    def clean_confirm_password(self):
        inputed_password=self.cleaned_data['password']
        inputed_confirm_password= self.cleaned_data['confirm_password']
        if inputed_password != inputed_confirm_password:
            raise ValidationError(f"Mật khẩu không khớp")
        return inputed_confirm_password

    def save_user(self):
        User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            email = self.cleaned_data['email'],
            first_name= self.cleaned_data['first_name'],
            last_name = self.cleaned_data['last_name']
        )

class LoginForm(Form):
    username = forms.CharField(
        label="Tên Đăng Nhập",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'id':'username'
            }
        )
    )

    password = forms.CharField(
        label="Mật Khẩu",
        widget=forms.PasswordInput(
             attrs={
                'class':'form-control',
                'id':'password'
            }
        )
    )

   

myapp/views.py
from django.core import paginator
from django.shortcuts import get_object_or_404, render,redirect,get_list_or_404
from django.http import HttpResponse, request
from django.core.paginator import Page, Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Book,Author
from .forms import AuthorForm, Bookform
# Create your views here.
def index(request): # Tham số bắt buộc phải có các hàm views.py 
    # # là resquest : httpresquest
    # print(request.GET['name']) #request.get nằm trên url khi mình gõ
    # name= request.GET.get('name','')
    # request.session['name'] = name
    # response= HttpResponse()
    # response.write("<h1> Alo Hello Thao</h1>")
    # response.write("Đây là app đầu tiên của Thao")
 
    # age=12
    # name="Alice"
    all_authors=Author.objects.all()
    return render(
        request=request,
        template_name="index.html",
    )
def home(request):
    name= request.session.get('name','')
    return HttpResponse('Hello' + name)

def list_author(request):
    all_authors= Author.objects.all()
    # paginator=Paginator(all_authors,5)
    # page_number = request.GET.get("page")
    # page_obj = paginator.get_page(page_number)
    search=request.GET.get('search')
    if search:
        all_authors=all_authors.filter(Q(first_name__icontains=search) | Q(last_name__icontains=search))
        # print(all_authors)
    return render(
        request=request,
        template_name="author/list.html",
        context={
            'all_authors':all_authors
        }
    )

@login_required(login_url="/login") # Dat decorator "login_required" bắt người dùng phải đăng nhập
def add_author(request):
    author_form=AuthorForm()
    if request.method == "POST":
        print(request.POST)
        author_form = AuthorForm(request.POST)
        if author_form.is_valid():   # hàm is_valid() nó gọi tất cả các hàm mà bắt đầu clean_
            print("Form validate OK")
            data = author_form.cleaned_data # cleand_data trong is_valid. tý bật lên sau
            author_form.save()
            return redirect("index")
    return render(
        request=request,
        template_name='author/add.html',
        context={
            'form': author_form
        }
    )
@login_required(login_url="/login")
def add_book(request):
    form_book = Bookform()
    if request.method == "POST":
        print(request.POST)
        form_book = Bookform(request.POST)
        if form_book.is_valid():   # hàm is_valid() nó gọi tất cả các hàm mà bắt đầu clean_
            print("Form validate OK")
            data = form_book.cleaned_data # cleand_data trong is_valid. tý bật lên sau
            form_book.save()
            return redirect("index")
    return render(
        request=request,
        template_name='book/add.html',
        context={
            'form': form_book
        }
    )
@login_required(login_url="/login")
def view_detail_author(request, author_id):
    author_data = Author.objects.get(id=author_id)
    return render(
        request=request,
        template_name= 'author/detail.html',
        context={
            'author': author_data
        }
    )
@login_required(login_url="/login")
def update_author(request, author_id):
    author_data = get_object_or_404(Author,id=author_id)
    author_form=AuthorForm(instance=author_data)
    if request.method == 'POST':
        author_data.first_name = request.POST.get('first_name',author_data.first_name)
        author_data.last_name = request.POST.get('last_name',author_data.last_name)
        author_data.email = request.POST.get('email',author_data.email)
        author_data.save()
        return redirect ("index")
    return render(
        request=request,
        template_name='author/update.html',
        context={
            'form': author_form
        }

    )
@login_required(login_url="/login")
def delete_author(request, author_id):
     author_data = get_object_or_404(Author,id=author_id)
     author_data.delete()
     return redirect ("index")

myapp/templates/author/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Add author</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                        {% if field.errors  %}
                            {% for error in field.errors %}
                                <p style="color: red;"> {{ error }} </p>
                            {% endfor %}
                        {% endif %}
                        </div> 
                    {% endfor %}
                    <input type="submit"  class="btn btn-success" value="Add author">
                </form>
            </div> 
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/author/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <h2>View detail author id {{ author.id }}</h2>
    <p>Name: {{ author.firt_name }} {{ author.last_name }}</p>
    <p>Email : {{ author.email }}</p>
    <h4>Danh sách các book:</h4>
    <ul>
        {% for book in author.book_set.all %}
           <li>{{ book.title }}</li> 
        {% endfor %}
    </ul>

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> -->
</body>
</html>

myapp/templates/author/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Author Hàm</title>
</head>
<body>
    <div class="container-fluide">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Mini3</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'list_author' %}">Author Hàm <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'all-author' %}">Author Class <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Book</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0" action="{% url 'list_author' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
              <ul class="nav justify-content-end">
                <li class="nav-item">
                  {% if user.is_authenticated %} <!--Đăng nhập thành công-->
                  <a class="nav-link" href="{% url 'logout_user' %}">Welcome {{ user.first_name }} {{ user.last_name }} | <i class="bi bi-lock"></i>Logout</a>
                  {% else %}
                  <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-unlock"></i>Login</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}"><i class="bi bi-person"></i>Register</a>
                </li>
              </ul>
            </div>
          </nav>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col">STT</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email </th>
                        <th scope="col"><a href="{% url 'add_author' %}"><i class="bi bi-plus-circle"></i></a></th>
                      </tr>
                    </thead>
                    <tbody>
                            {% for author in all_authors %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="{% url 'view_detail_author' author_id=author.id %}">{{ author.first_name }}</a></td>
                                    <td>{{ author.last_name }}</td>
                                    <td>{{ author.email }}</td>
                                    <td>
                                        <a href="{% url 'view_detail_author' author_id=author.id %}"><i class="bi bi-eye"></i></a>
                                        | <a href="{% url 'update_author' author_id=author.id %}"><i class="bi bi-pencil"></i></a>
                                        | <a href="{% url 'delete_author' author_id=author.id %}"><i class="bi bi-trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}        
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/author/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Add author</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                        {% if field.errors  %}
                            {% for error in field.errors %}
                                <p style="color: red;"> {{ error }} </p>
                            {% endfor %}
                        {% endif %}
                        </div> 
                    {% endfor %}
                    <input type="submit"  class="btn btn-success" value="Update author">
                </form>
            </div> 
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>